spring:
  datasource:
    url: jdbc:mysql://localhost:3306/app_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root

  data:
    redis:
      host: localhost
      port: 6379
  
  profiles:
    active: dev

app:
  jwt:
    secret: "CHANGE_ME_TO_A_LONG_RANDOM_SECRET_32+_CHARS"
    expire-seconds: 
    
aws:
  s3:
    bucket: swapspot-dev-assets