spring:
  application:
    name: swapspot

  jackson:
    time-zone: UTC

  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.cyanzone.swapspot.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: INFO
    # com.zaxxer.hikari: DEBUG
    # org.mybatis: DEBUG

aws:
  region: us-east-2
